"""
Paths shared by every script in the project — a single place to change if
the folder layout ever moves.

Expected project structure (see README.md at the root):

    monthly_reporting/                  <- project root (holds pyproject.toml, .venv, ...)
    ├── input_data/                     <- indicator reference + long-format raw data (1 single
    │                                      consolidated file, all BUs) : OUTPUT of
    │                                      extract_reference_and_data.py, INPUT of
    │                                      generate_data_entry_file.py and csr_calc_engine.py
    ├── output_data/                    <- consolidated results : OUTPUT of csr_calc_engine.py
    └── scripts/                        <- the code (this file + the scripts) — no src/, no
        ├── config.py                      __init__.py: these aren't modules of a package
        ├── extract_reference_and_data.py  meant to be imported from outside, just scripts
        ├── generate_data_entry_file.py     that get run directly.
        ├── integrate_data_entry.py
        └── csr_calc_engine.py

Two folders on purpose are NOT inside this project — they are read from /
written directly to the shared SharePoint drive instead, because this whole
project already lives inside the same synced library
(.../CSR referents - Documents/General/...), so those folders are just as
reachable as anything inside the project itself. No manual copying in either
direction, no local staging folder:

  - RAW_DATA_DIR = .../General/Monthly reporting/Archives/
    The 6 original raw workbooks (12-tab-per-BU, never modified by this
    project). Read ONCE by extract_reference_and_data.py, to convert them
    into the new format (input_data/) — the historical backfill. Not part
    of the regular monthly cycle: once that conversion is done, this folder
    and that script are never touched again.

    NOTE — this will need updating once Bioline retires the "Archives"
    subfolder (expected around Sept. 2026): the 6 files will then live
    directly in .../General/Monthly reporting/ instead, one level up. Since
    this only matters for that one-time historical read, there is no rush
    to change it before then.

  - DATA_ENTRY_DIR = .../General/Monthly reporting/
    Where generate_data_entry_file.py writes each BU's monthly file
    (<BU>_data_entry_CSR.xlsm) and integrate_data_entry.py reads it back
    from, once the referent has filled it in. Every BU's CSR referent
    already has standing access to this folder — nothing needs to be
    emailed or sent around, and there is no separate "data_entry/" folder
    inside this project.

This file computes these paths once, based on this file's own location
(regardless of the directory `uv run ...` is launched from), and creates the
input_data/output_data folders if they don't exist yet.
"""
from pathlib import Path

# This file lives at <root>/scripts/config.py:
#   parents[0] = scripts
#   parents[1] = <project root> (.../General/Reporting_Automation/monthly_reporting)
#   parents[2] = .../General/Reporting_Automation
#   parents[3] = .../General
PROJECT_ROOT = Path(__file__).resolve().parents[1]

MONTHLY_REPORTING_DIR = PROJECT_ROOT.parents[1] / "Monthly reporting"
RAW_DATA_DIR = MONTHLY_REPORTING_DIR / "Archives"
DATA_ENTRY_DIR = MONTHLY_REPORTING_DIR
INPUT_DIR = PROJECT_ROOT / "input_data"
OUTPUT_DIR = PROJECT_ROOT / "output_data"

INPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Names of the 6 original raw Excel files, exactly as provided by Bioline.
# Used by extract_reference_and_data.py (required) and by csr_calc_engine.py
# (only for the optional one-off validation).
RAW_FILES = {
    "Viridaxis": "Bioline monthly reporting - Viridaxis.xlsx",
    "BAF": "Bioline monthly reporting - BAF.xlsx",
    "BFR": "Bioline monthly reporting - BFR.xlsx",
    "BIB": "Bioline monthly reporting - BIB.xlsx",
    "BUK": "Bioline monthly reporting - BUK.xlsx",
    "BUS": "Bioline monthly reporting - BUS.xlsx",
}

# Month-over-month variation threshold above which the "Annual summary" tab
# (generated by generate_data_entry_file.py) highlights a cell in red, and
# above which csr_calc_engine.py's anomaly report flags a value as an
# outlier. 0.20 = 20%.
VARIATION_THRESHOLD = 0.20

# Anomaly report emailed automatically at the end of every
# csr_calc_engine.py run (data quality corrections, missing values, large
# variations) — see scripts/consolidation_report.py. Sent through the local
# Outlook desktop app, no password stored anywhere.
SEND_ERROR_REPORT_EMAIL = True  # set to False to stop sending it

REPORT_RECIPIENTS = [
    "athebault@biolineagrosciences.com",
]
