"""
Integrates a monthly data entry file filled in by a CSR referent
(config.DATA_ENTRY_DIR/<BU>_data_entry_CSR.xlsm, generated by
generate_data_entry_file.py, in the shared SharePoint folder — see
config.py) into the BU's long-format raw data (input_data/Raw_data_CSR.xlsx)
— this is what csr_calc_engine.py reads next.

Reuses the same parsing as the initial extraction (decimal comma, unparsable
text -> tracked data quality note) to stay consistent with
extract_reference_and_data.py.

Rows are identified by the "ID" column of the data entry file (never by row
position), so this still works even if the referent sorted or moved rows
around.

Usage
-----
    uv run scripts/integrate_data_entry.py BAF          # one BU
    uv run scripts/integrate_data_entry.py              # all 6 BUs (those
                                                          # whose data entry file exists)

Follow up with:
    uv run scripts/csr_calc_engine.py

Dependencies: pandas, openpyxl.
"""
import re
import sys
from pathlib import Path

import openpyxl
import pandas as pd
from openpyxl.worksheet.table import Table, TableStyleInfo
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.worksheet.protection import SheetProtection
from openpyxl.styles import PatternFill, Font, Protection
from openpyxl.utils import get_column_letter

sys.path.insert(0, str(Path(__file__).resolve().parent))
import config
from generate_data_entry_file import DISPLAY_COLS

MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]

FRENCH_DECIMAL_RE = re.compile(r"^\s*-?\d+,\d+\s*$")

ORANGE = "FFFFC000"
YELLOW_NOTE = "FFFFF2CC"
HEADER_FILL = "1F3864"


def parse_raw_value(v):
    """Same logic as in extract_reference_and_data.py — see that file for
    the rationale behind each case."""
    if v is None:
        return None, None
    if isinstance(v, (int, float)):
        return float(v), None
    if isinstance(v, str):
        s = v.strip()
        if not s:
            return None, None
        if FRENCH_DECIMAL_RE.match(s):
            return float(s.replace(",", ".")), "Corrected: decimal comma (“" + v + "”) -> dot"
        try:
            return float(s), "Corrected: numeric text -> number"
        except ValueError:
            return None, f"NOT PARSABLE, needs a manual fix in the data entry file: “{v}”"
    return None, f"Unexpected type ({type(v).__name__}): {v!r}"


def read_data_entry_file(bu: str) -> pd.DataFrame:
    """Reads the data entry file filled in by a BU's CSR referent
    (config.DATA_ENTRY_DIR/<BU>_data_entry_CSR.xlsm) and extracts, for each
    month, the value and comment typed into the "Value of the month" /
    "Comment" columns — relying on the "ID" column to identify each row
    (never its position), so this still works even if rows were moved or
    sorted in the file. The value is cleaned along the way (see
    parse_raw_value)."""
    path = config.DATA_ENTRY_DIR / f"{bu}_data_entry_CSR.xlsm"
    if not path.exists():
        raise FileNotFoundError(f"Data entry file not found: {path}")
    wb = openpyxl.load_workbook(path, data_only=True)
    value_col = len(DISPLAY_COLS) + 2
    comment_col = value_col + 1
    records = []
    for month in MONTHS:
        if month not in wb.sheetnames:
            continue
        ws = wb[month]
        for r in range(2, ws.max_row + 1):
            idv = ws.cell(row=r, column=1).value  # "ID" column
            if not idv:
                continue
            raw_value = ws.cell(row=r, column=value_col).value    # "Value of the month"
            comment = ws.cell(row=r, column=comment_col).value    # "Comment"
            value, note = parse_raw_value(raw_value)
            records.append({"Month": month, "ID": idv, "Value": value, "Comment": comment,
                             "Data quality note": note})
    return pd.DataFrame(records)


def load_consolidated() -> pd.DataFrame:
    """input_data/Raw_data_CSR.xlsx — a single file, all BUs combined (see
    extract_reference_and_data.py for the rationale: simpler to manage than
    6 files, correct as long as this script is called as a SINGLE process
    that loops over the requested BUs, never several concurrent processes
    writing this same file in parallel — which main() does not do)."""
    path = config.INPUT_DIR / "Raw_data_CSR.xlsx"
    if path.exists():
        return pd.read_excel(path, sheet_name="Raw_data")
    return pd.DataFrame(columns=["BU", "Month", "ID", "Value", "Comment", "Data quality note"])


def export_consolidated(df: pd.DataFrame):
    """Rewrites input_data/Raw_data_CSR.xlsx with the same conventions as
    extract_reference_and_data.py (same protections, formatting, structured
    Table)."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Raw_data"
    ws.append(list(df.columns))
    for cell in ws[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color=HEADER_FILL, end_color=HEADER_FILL, fill_type="solid")
    for row in df.itertuples(index=False):
        ws.append(list(row))
        for c in ws[ws.max_row]:
            if isinstance(c.value, str) and c.value.startswith("="):
                c.data_type = "s"
    last_row = df.shape[0] + 1
    last_col = get_column_letter(df.shape[1])
    for col_cells in ws.columns:
        length = max((len(str(c.value)) if c.value is not None else 0) for c in col_cells)
        ws.column_dimensions[col_cells[0].column_letter].width = min(max(length + 2, 10), 60)
    ws.freeze_panes = "A2"

    value_col = list(df.columns).index("Value") + 1
    comment_col = list(df.columns).index("Comment") + 1
    note_col = list(df.columns).index("Data quality note") + 1

    for r in range(2, last_row + 1):
        for c in range(1, df.shape[1] + 1):
            ws.cell(row=r, column=c).protection = Protection(locked=True)
        vcell = ws.cell(row=r, column=value_col)
        ccell = ws.cell(row=r, column=comment_col)
        vcell.protection = Protection(locked=False)
        ccell.protection = Protection(locked=False)
        vcell.fill = PatternFill(start_color=ORANGE, end_color=ORANGE, fill_type="solid")
        if ws.cell(row=r, column=note_col).value:
            ws.cell(row=r, column=note_col).fill = PatternFill(
                start_color=YELLOW_NOTE, end_color=YELLOW_NOTE, fill_type="solid")

    dv = DataValidation(type="decimal", operator="greaterThanOrEqual", formula1="0", allow_blank=True,
                         showErrorMessage=True, errorTitle="Invalid value",
                         error="Please enter a number >= 0.")
    ws.add_data_validation(dv)
    dv.add(f"{get_column_letter(value_col)}2:{get_column_letter(value_col)}{last_row}")

    tbl = Table(displayName="Raw_Data_CSR", ref=f"A1:{last_col}{last_row}")
    tbl.tableStyleInfo = TableStyleInfo(name="TableStyleMedium2", showRowStripes=True)
    ws.add_table(tbl)

    ws.protection = SheetProtection(sheet=True, password=None, formatCells=False, formatColumns=False,
                                     formatRows=False, autoFilter=False, sort=False,
                                     selectLockedCells=False, selectUnlockedCells=False,
                                     objects=False, scenarios=False)

    wb.save(config.INPUT_DIR / "Raw_data_CSR.xlsx")


def main():
    """Entry point: integrates into the consolidated data
    (input_data/Raw_data_CSR.xlsx) the values typed by the CSR referents
    into their data entry file(s) (config.DATA_ENTRY_DIR/<BU>_data_entry_CSR.xlsm),
    for one or more BUs (all those whose file exists, by default). First
    re-reads everything that already exists, only replaces the rows
    affected by the new entries (everything else is left untouched), then
    rewrites the consolidated file in a single pass at the end. Run this
    after the referent(s) have filled in their file, and before running
    csr_calc_engine.py to recalculate the indicators."""
    requested = sys.argv[1:] or list(config.RAW_FILES.keys())

    # A single read of the consolidated file, a single write at the end —
    # the requested BUs are processed one after another IN MEMORY, in this
    # same process.
    combined = {(r["BU"], r["Month"], r["ID"]): r for r in load_consolidated().to_dict("records")}

    processed = []
    for bu in requested:
        try:
            new_df = read_data_entry_file(bu)
        except FileNotFoundError as e:
            print(f"{bu}: {e}")
            continue
        for r in new_df.to_dict("records"):
            r["BU"] = bu
            combined[(bu, r["Month"], r["ID"])] = r  # overwrites the existing row (or creates a new one)
        processed.append(bu)

        flagged = new_df[new_df["Data quality note"].notna()]
        print(f"{bu}: {len(new_df)} values read from the data entry file"
              + (f", {len(flagged)} quality note(s)" if len(flagged) else ""))
        if len(flagged):
            print(flagged[["Month", "ID", "Value", "Data quality note"]].to_string(index=False))

    if not processed:
        print("Nothing to integrate (no data entry file found).")
        return

    merged = pd.DataFrame(combined.values())
    merged["Month"] = pd.Categorical(merged["Month"], categories=MONTHS, ordered=True)
    merged = merged[["BU", "Month", "ID", "Value", "Comment", "Data quality note"]]
    merged = merged.sort_values(["BU", "Month", "ID"]).reset_index(drop=True)
    export_consolidated(merged)
    print(f"\n{config.INPUT_DIR / 'Raw_data_CSR.xlsx'} updated "
          f"({len(processed)} BU(s) integrated in a single write: {', '.join(processed)}).")


if __name__ == "__main__":
    main()
